### PR TITLE
Pass Window to Callback

### PR DESCRIPTION
**Pull request by pcavanaugh**
Pass `window` to the callback so consumers of scraper can free the memory used by jsdom.

### CODE REVIEW

**Comment by boblauer** [comment]
:dancer: :dancer: :dancer: 

:+1:

**Comment by jduh** [comment]
:shipit:

**Comment by tylerwhipple** [comment]
:shipit:

**Comment by boblauer** [comment]
@tylerwhipple approved.  What more could you ask for?

**Pull request merged**
